apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.foocontroller.k8s.io
webhooks:
- name: validation.foocontroller.k8s.io
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/validation.foocontroller.k8s.io/v1alpha1/admissionreviews
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - UPDATE
    apiGroups:
    - foocontroller.k8s.io
    apiVersions:
    - "*"
    resources:
    - "*"
  failurePolicy: Fail
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutation.foocontroller.k8s.io
webhooks:
- name: mutation.foocontroller.k8s.io
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/mutation.foocontroller.k8s.io/v1alpha1/admissionreviews
    caBundle: ${KUBE_CA}
  rules:
  - operations:
    - CREATE
    apiGroups:
    - foocontroller.k8s.io
    apiVersions:
    - "*"
    resources:
    - "*"
  failurePolicy: Fail